****************************
*** Sensitivity Analysis ***
****************************


*** Variable Description ***

* functional_neu: Number of functional health limitations (sum of ADL and mobility limitations) - fully time-varying, continuous scale

* eurod: EURO-D scale (generated by SHARE, imputed version from SUF) - fully time-varying, continuous scale 

* edu_cat: Highest educational level, four cateogries: 0"Lower than ISCED1 or n.a." 1"ISCED 1 or 2" 2"ISCED 3 or 3" 3"ISCED 5 or 6" - non-timevarying, categorical (ordered)

* vigorous_weekly: Performs vigorous physical activity at least weekly (1=yes), recoded from original scale - fully time-varying, dichotomous

* moderate_weekly: Performs moderate physical activity at least weekly (1=yes), recoded from original scalre - fully time-varying, dichotomous

* empl4neu: Current employment situation: 1"Full-time" 2"Part-time" 3"Retired" 4"Inactive", recoded from variable cjs in imputed data set - fully time-varying, categorical (unordered)

* sectors_new: Type of sector respondent works in (current, if employed) or worked in (last job, of not employed), information from SHARELIFE: - non time-varying, categorical (ordered)

* soc_act: Takes part in social activities at least weekly (1=yes), recoded from original variables pertaining to meeting others, volunteering playing cards, being in a sports or church association. Fully time-varying, dichotomous

* educ_act: Takes part in cognitively stimulating or educational activity at least weekly (1=yes), recoded from original variables pertaining to being part of a political or educational group, a reading circle, doing quizzes and puzzles. Fully time-varying, dichotomous

* civilneu2: recoded from civilstatus, partner in household and change in civil status variables 1"Partnered" 2"Re-partnered (after divorce or widowhood)" 4"Never married (and not cohabiting)" 5"Divorced" 6"Widowed" - fully time-varying, categorical scale level (unordered)

*i_nchild_neu: Total number of children, taken from generated variables (imputed). Recoded to cap at 7 children (>7 children are coded to 7).  Fully time-varying, continuous

*i_ngrchild_neu: Total number of grandchildren (biological and non-biological), taken from generated varialbes (imputed). Fully time-varying, continuous

* given: Has given help or care to someone outside the household (1=yes) - fully-time varying, dichotomous

* received: Has received help or care from someone outside the household (1=yes) - fully time-varying, dichotomous

* ends_neu: Household can make ends meet 1"With great difficulty" - 4"Easily", from generated data file (imputed) - fully time-varying, used as categorical variable (ordered)

* born in country: Respondent bar born in country of interview (1=yes), from DN module, baseline observation, carried forward - not time-varying, dichtomous

* female: Woman (1=yes)

* i.sharecohort: Recoded from birthyear: 1"Born before 1920" 2"Born 1920-1929" 3"Born 1930-1939" 4"Born 1940-1949" 5"Born 1959-1959" 6"Born 1960-1969" 7"Born 1970-1979" 8"Born 1980 or later" - Non-timevarying, categorical (ordered)

* age_baseline: Recoded from birthyear (-> age) and wave year: Age at baseline interview. Non time-varying, continuous

*agebase2: Square term of age_baseline

* time: recoded from each interview year. First interview is set to "0", thereafter each interview is coded with how many years have passed since baseline

* time_sq: Square term of time-varying



*** Predict listwise missing (0=missing, 1=not listwise deleted) ***
* with the variables used in the models *

log using sensitivity_nomiss.smcl, replace

/*mark nomiss1
markout nomiss1 functional_neu eurod edu_cat eurod vigorous_weekly moderate_weekly empl4neu sectors_new soc_act educ_act civilneu2 i_nchild_neu i_ngrchild_neu given received ends_neu born_in_country female sharecohort age_baseline agebase2

global controls functional_neu eurod i.edu_cat eurod vigorous_weekly moderate_weekly i.empl4neu i.sectors_new soc_act educ_act i.civilneu2 i_nchild_neu i_ngrchild_neu given received i.ends_neu born_in_country female i.sharecohort age_baseline agebase2 rs_ft rs_pt rs_homemaking rs_unemployed rs_otherneu
*/



* Joint *

*** Demographic Factors ***
 xtlogit nomiss1 female functional_neu  eurod ib1.sharecohort age_baseline agebase2  i.wave if agegr5075==1&obs>1&cogfilt_conservative==1&rs_miss_filt==0&eurod<5, re
 
*** Previous Emplyoment Biographies ***
 xtlogit nomiss1 rs_ft rs_pt rs_unemp rs_homemaking rs_otherneu i.wave if agegr5075==1&obs>1&cogfilt_conservative==1&rs_miss_filt==0&eurod<5, re
 
*** Socio-Economic Factors ***
 xtlogit nomiss1 ib1.edu_cat ib1.empl4neu  ib2.ends_neu born_in_country i.wave if agegr5075==1&obs>1&cogfilt_conservative==1&rs_miss_filt==0&eurod<5, re

*** Occupation Characteristics ***
 xtlogit nomiss1 i.sectors_new i.job_stim_neu i.job_agency_neu i.wave if agegr5075==1&obs>1&cogfilt_conservative==1&rs_miss_filt==0&eurod<5, re
 
*** Family Situation and Family Roles ***
xtlogit nomiss1  ib1.civilneu2 i_nchild_neu i_ngrchild_neu given received i.wave if agegr5075==1&obs>1&cogfilt_conservative==1&rs_miss_filt==0&eurod<5, re

*** Retrospective Family ***
xtlogit nomiss1  rs_withpartner rs_withchildren i.wave if agegr5075==1&obs>1&cogfilt_conservative==1&rs_miss_filt==0&eurod<5, re


* Men *
*** Demographic Factors ***
 xtlogit nomiss1 female functional_neu  eurod ib1.sharecohort age_baseline agebase2  i.wave if agegr5075==1&obs>1&cogfilt_conservative==1&rs_miss_filt==0&eurod<5&female==0, re
 
*** Previous Emplyoment Biographies ***
 xtlogit nomiss1 rs_ft rs_pt rs_unemp rs_homemaking rs_otherneu i.wave if agegr5075==1&obs>1&cogfilt_conservative==1&rs_miss_filt==0&eurod<5&female==0, re
 
*** Socio-Economic Factors ***
 xtlogit nomiss1 ib1.edu_cat ib1.empl4neu  ib2.ends_neu born_in_country i.wave if agegr5075==1&obs>1&cogfilt_conservative==1&rs_miss_filt==0&eurod<5&female==0, re

*** Occupation Characteristics ***
 xtlogit nomiss1 i.sectors_new i.job_stim_neu i.job_agency_neu i.wave if agegr5075==1&obs>1&cogfilt_conservative==1&rs_miss_filt==0&eurod<5&female==0, re
 
*** Family Situation and Family Roles ***
xtlogit nomiss1  ib1.civilneu2 i_nchild_neu i_ngrchild_neu given received i.wave if agegr5075==1&obs>1&cogfilt_conservative==1&rs_miss_filt==0&eurod<5&female==0, re

*** Retrospective Family ***
xtlogit nomiss1  rs_withpartner rs_withchildren i.wave if agegr5075==1&obs>1&cogfilt_conservative==1&rs_miss_filt==0&eurod<5&female==0, re


* Women *
*** Demographic Factors ***
 xtlogit nomiss1 female functional_neu  eurod ib1.sharecohort age_baseline agebase2  i.wave if agegr5075==1&obs>1&cogfilt_conservative==1&rs_miss_filt==0&eurod<5&female==1, re
 
*** Previous Emplyoment Biographies ***
 xtlogit nomiss1 rs_ft rs_pt rs_unemp rs_homemaking rs_otherneu i.wave if agegr5075==1&obs>1&cogfilt_conservative==1&rs_miss_filt==0&eurod<5&female==1, re
 
*** Socio-Economic Factors ***
 xtlogit nomiss1 ib1.edu_cat ib1.empl4neu  ib2.ends_neu born_in_country i.wave if agegr5075==1&obs>1&cogfilt_conservative==1&rs_miss_filt==0&eurod<5&female==1, re

*** Occupation Characteristics ***
 xtlogit nomiss1 i.sectors_new i.job_stim_neu i.job_agency_neu i.wave if agegr5075==1&obs>1&cogfilt_conservative==1&rs_miss_filt==0&eurod<5&female==1, re
 
*** Family Situation and Family Roles ***
xtlogit nomiss1  ib1.civilneu2 i_nchild_neu i_ngrchild_neu given received i.wave if agegr5075==1&obs>1&cogfilt_conservative==1&rs_miss_filt==0&eurod<5&female==1, re

*** Retrospective Family ***
xtlogit nomiss1  rs_withpartner rs_withchildren i.wave if agegr5075==1&obs>1&cogfilt_conservative==1&rs_miss_filt==0&eurod<5&female==1, re



*** Predict Outcome bivariately with each of these factors ***

* First with full sample (all available observations), then with listwise deleted sample *
* Time trend is always adjusted for *

** Null Model **
* Men *
mixed z_cogscore time time_sq || mergeid: time if agegr5075==1&cogfilt_conservative==1&female==0&nomiss_macros==1&rs_miss_filt==0&eurod<5 
est sto r_all_null

mixed z_cogscore time time_sq || mergeid: time if agegr5075==1&cogfilt_conservative==1&female==0&nomiss_macros==1&rs_miss_filt==0&eurod<5&nomiss1==1
est sto r_lw_null

foreach x of global controls {
mixed z_cogscore `x' time time_sq || mergeid: time if agegr5075==1&cogfilt_conservative==1&female==0&nomiss_macros==1&rs_miss_filt==0&eurod<5 
mixed z_cogscore `x' time time_sq || mergeid: time if agegr5075==1&cogfilt_conservative==1&female==0&nomiss_macros==1&rs_miss_filt==0&eurod<5&nomiss1==1
}

* Women *
mixed z_cogscore time time_sq || mergeid: time if agegr5075==1&cogfilt_conservative==1&female==1&nomiss_macros==1&rs_miss_filt==0&eurod<5 
est sto r_all_null

mixed z_cogscore time time_sq || mergeid: time if agegr5075==1&cogfilt_conservative==1&female==1&nomiss_macros==1&rs_miss_filt==0&eurod<5&nomiss1==1
est sto r_lw_null

foreach x of global controls {
mixed z_cogscore `x' time time_sq || mergeid: time if agegr5075==1&cogfilt_conservative==1&female==1&nomiss_macros==1&rs_miss_filt==0&eurod<5 
mixed z_cogscore `x' time time_sq || mergeid: time if agegr5075==1&cogfilt_conservative==1&female==1&nomiss_macros==1&rs_miss_filt==0&eurod<5&nomiss1==1
}


log close

